config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end

  resources :doses, only: [ :destroy ]


root :to => "cocktails#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy;
  has_many :ingredients, through: :doses;
  validates :name, uniqueness: true, presence: true;
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail;
  belongs_to :ingredient;
  validates_presence_of :description, :cocktail, :ingredient
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses;
  validates :name, uniqueness: true, presence: true;

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def home
  end


  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredients, :doses, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    # @cocktail = Cocktail.find(params[:cocktail_id])
    # @ingredient = Ingredient.find(params[:ingredient_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(review_params)
    # we need `cocktail_id/ingredient_id` to asssociate review with corresponding restaurant
    @dose.cocktail = @cocktail
    @cocktail = @dose.cocktail
    @dose.ingredient = Ingredient.find(params["dose"]["ingredient_id"])
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
     @dose = Dose.find(params[:id])
     cocktail = @dose.cocktail
     @dose.destroy
     redirect_to cocktail_path(cocktail)
  end

  private

  def review_params
    params.require(:dose).permit(:description)
  end

  def set_cocktail
   @cocktail = Cocktail.find(params[:cocktail_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1507434965515-61970f2bd7c6?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=9fb72c1c53fe03421b3b914c7444d13c&auto=format&fit=crop&w=634&q=80');">
  <div class="banner-content">
    <h1>Le Wagon Cocktails Bar</h1>
    <p>Learn to code and drink a lot, life is now</p>
    <%= link_to "Cocktails", cocktails_path %>
    <!-- <a href="/cocktails" class="btn btn-primary btn-lg"><i class="fa fa-glass-martini"></i></a> -->
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="wrapper">
  <%= render 'shared/navbar' %>
  <div class="banner" id="banner2" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1508253730651-e5ace80a7025?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cf395e42474f855162357f6f556e8b47&auto=format&fit=crop&w=500&q=60');">
    <div class="banner-content">
      <h1>All Cocktails</h1>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path(cocktail.photo) %>');">
          <div class="card-description">
            <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div>
  <%= render 'shared/navbar' %>
  <div>
    <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1461823385004-d7660947a7c0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=82c2b0959f392571810e512b4a73d625&auto=format&fit=crop&w=500&q=60');">
      <div class="banner-content">
        <h1>Create your favorite Cocktail</h1>
          <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name, placeholder: "Insert the name of your cocktail here", label: false %>
          <p>Upload your cocktail photo below</p>
          <%= f.input :photo, label: false %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="footer">
    <div class="footer-links">
      <%= link_to "Cocktails", cocktails_path %>
      <a href="/"><i class="fa fa-glass-martini"></i></a>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div>
  <%= render 'shared/navbar' %>
  <div>
    <div class="banner" style="background-image: url('<%= cl_image_path @cocktail.photo, height: 300, width: 400, crop: :fill %>');">
      <div class="banner-content uptext">
        <h2><%= @cocktail.name %></h2>
        <% @cocktail.doses.each do |dose| %>
          <li><%= dose.description %> - <%= dose.ingredient.name %>
            <%= link_to dose, method: :delete do %>
            <i class="fa fa-trash"></i>
            <% end %>
          </li>
        <% end %>
        <%= link_to "New Dose", new_cocktail_dose_path(@cocktail) %>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer">
    <div class="footer-links">
      <%= link_to "Cocktails", cocktails_path %>
      <a href="/"><i class="fa fa-glass-martini"></i></a>
      <a href="/"><i class="fal fa-trash-alt"></i></a>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div>
  <%= render 'shared/navbar' %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1507123948929-86a949bdaa23?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a5d65ee5a94e0bab030c5f698216b9da&auto=format&fit=crop&w=500&q=60');">
    <div class="banner-content">
      <h1>Creating new doses</h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description, placeholder: "Insert your doses here", label: false %>
        <p>Select one ingredient below</p>
        <%= f.association :ingredient, label: false %>
        <%= f.submit "add a dose", class: "btn btn-primary" %>
      <% end %>
      <hr>
      <%= link_to "Cocktails", cocktails_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="<%= image_path("logo.png") %>" alt="logo">
  </a>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="http://lefumoir.com/elements/bar-vins.pdf" target="_blank" class="navbar-wagon-item navbar-wagon-link">Menu</a>
    <a href="https://www.lewagon.com/es/barcelona" target="_blank" class="navbar-wagon-item navbar-wagon-link">Contact</a>
    <a href="https://www.google.es/maps/place/Le+Wagon+Barcelona+Coding+Bootcamp/@41.4054048,2.1627273,17z/data=!3m1!4b1!4m5!3m4!1s0x12a4a2c0a8c11443:0x3c4b676b305f1842!8m2!3d41.4054048!4d2.164916" target="_blank" class="navbar-wagon-item navbar-wagon-link">Address</a>
    <a href='/cocktails/new' target="_blank" class="btn-medium">Create a new cocktail</a>
  </div>
</div>